### ISSUE TITLE
Vue Toast

### ISSUE THREAD

**Issue by w1lldone** [bppugm/publication-dashboard#23]
https://www.npmjs.com/package/vue-toast-notification
https://ankurk91.github.io/vue-toast-notification/

**Comment by w1lldone** [comment]
@michaelr1300 @ebifurei Belum ada yang install toast buat response success atau error kan? Mau pakai ini

**Comment by ebifurei** [comment]
@w1lldone Belum mas

**Comment by michaelr1300** [comment]
Belum mas
